services:

  grobid:
    image: grobid/grobid:0.8.1
    ports:
      - "8070:8070"

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: article-processor
    volumes:
      - ~/volumes/tmp/mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
